### ISSUE TITLE
'toLowerCase' error

### ISSUE THREAD

**Issue by SdeGeata** [nischi/MMM-Face-Reco-DNN#12]
Hello again;

After some time away on other projects, I have finally gotten back to straightening out my last installation of your module. 

> python3 facerecognition.py < runs the facial recognition fine and recognizes me - this in a nice change from the other installations I tried. However, I am getting this new error from the electron console on the mirror:

 `Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at main.js:398
    at Array.filter (<anonymous>)
    at modulesByClass (main.js:397)
    at Array.withClass (main.js:369)
    at Class.login_user (:8080/modules/MMM-Fa…Face-Reco-DNN.js:67)
    at Class.socketNotificationReceived (:8080/modules/MMM-Fa…ace-Reco-DNN.js:137)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (socket.io.js:6)
    at r.onevent (socket.io.js:8)
main.js:398 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at main.js:398
    at Array.filter (<anonymous>)
    at modulesByClass (main.js:397)
    at Array.withClass (main.js:369)
    at Class.logout_user (:8080/modules/MMM-Fa…ace-Reco-DNN.js:106)
    at :8080/modules/MMM-Fa…ace-Reco-DNN.js:152`

**Comment by nischi** [comment]
Have you changed something that this error pops up?

**Comment by SdeGeata** [comment]
No, I didn't change a thing. Once i finally got all the things to install, I only tested it by running with python - not on the mirror directly, then I became busy with another project.

Should I uninstall and do a clean installation of Facial Recognition? Do you think that would help?

**Comment by SdeGeata** [comment]
So I reinstalled Facial Recognition, as well as your module. I am still getting the same error.

**Comment by nischi** [comment]
Okay, strange. Can you please send me a screenshot of your folderstructure, specialy where you have your images in?

**Comment by SdeGeata** [comment]
Hello again Thierry;

   So this is the folder structure from Magic Mirror on down. Hopefully we can easily find the problem.

**Comment by nischi** [comment]
@SdeGeata Hmmm strange, the Attachment has not working via mail, i do not see them, sorry.

**Comment by nischi** [comment]
Thanks, looks fine to me so far. will check that this week whats going on.

**Comment by nischi** [comment]
do you have a message like "[MMM-Face-Reco-DNN] Users [SOMETHING] logged in." in the log? I do not find the issue. I will try to add a check, but that only solve the symptom.

**Comment by nischi** [comment]
@SdeGeata I have pushed a fix to master. Can you test it, please? I can't reproduce the issue but that should solve it.

**Comment by SdeGeata** [comment]
Hello Thierry;

   So I'm back at it again. I did a clean install of the module, re-encoded the dataset and tried it again. It is still not revealing my module, and is throwing the following 2 errors in electron console:

`main.js:398 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at main.js:398
    at Array.filter (<anonymous>)
    at modulesByClass (main.js:397)
    at Array.withClass (main.js:369)
    at Class.login_user (MMM-Face-Reco-DNN.js:72)
    at Class.socketNotificationReceived (MMM-Face-Reco-DNN.js:143)
    at module.js:246
    at r.<anonymous> (socketclient.js:25)
    at r.emit (index.js:83)
    at r.onevent (index.js:83)
main.js:398 Uncaught TypeError: Cannot read property 'toLowerCase' of undefined
    at main.js:398
    at Array.filter (<anonymous>)
    at modulesByClass (main.js:397)
    at Array.withClass (main.js:369)
    at Class.logout_user (MMM-Face-Reco-DNN.js:111)
    at MMM-Face-Reco-DNN.js:160`

I tested with the facerecognition.py, that works fine:

`pi@betyar:~/MagicMirror/modules/MMM-Face-Reco-DNN/tools $ python3 facerecognition.py
{"status": "loading encodings + face detector..."}
{"status": "starting video stream..."}
{"login": {"names": ["Stiofan"]}}
{"logout": {"names": ["Stiofan"]}}
{"login": {"names": ["Stiofan"]}}
{"logout": {"names": ["Stiofan"]}}
{"login": {"names": ["Stiofan"]}}
{"logout": {"names": ["Stiofan"]}}
{"login": {"names": ["Gab"]}}
{"logout": {"names": ["Gab"]}}
^C
{"status": "elasped time: 167.27"}
{"status": "approx. FPS: 0.25"}
`

I really am at a loss here. I just want this thing to work.

**Comment by nischi** [comment]
Really strange. What hardware do you have?

**Comment by SdeGeata** [comment]
Raspberry pi 3b+ running Stretch with a Picam noir 2. All prerequisites for your module are installed. Strange indeed.

**Comment by nischi** [comment]
The hardware shouldn't be a problem then. Hmm.... can you send me your full MM Config?

**Comment by SdeGeata** [comment]
Sure, how can I pm you?

**Comment by nischi** [comment]
Send me a mail to github@nischi.ch

**Comment by SdeGeata** [comment]
Sent!
